name: CI

on:
  pull_request:
  push:
    branches: ['master']
    tags: ['v*']
  schedule:
  - cron: '00 01 * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build:
        - win-msvc
        - macos
        - linux-gnu
        - linux-aarch64
        - linux-armv7
        include:
        - build: win-msvc
          os: windows-latest
        - build: macos
          os: macos-latest
        - build: linux-gnu
          os: ubuntu-20.04
        - build: linux-aarch64
          os: ubuntu-latest
          target: aarch64-unknown-linux-gnu
        - build: linux-armv7
          os: ubuntu-latest
          target: armv7-unknown-linux-gnueabihf

    steps:
    - uses: actions/checkout@v1
    - name: Use Cross
      if: matrix.target != ''
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET=${{ matrix.target }}" >> $GITHUB_ENV
    - name: Use Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install wasm-pack
      run:  curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh 
    - name: npm install & build
      shell: bash
      run: |
        npm install
        npm run build:web
        npm run build:native -- ${TARGET:+--target "$TARGET"}
        npm run build
    - name: npm test
      if: matrix.target == ''
      shell: bash
      run: npm test
    - name: browser test
      working-directory: ./e2e
      if: matrix.target == ''
      run: |
        npm install
        npm test
    - name: strip linux builds
      if: matrix.build == 'linux-gnu'
      run: strip dist/node/*.node
    - name: strip linux-aarch64 builds
      if: matrix.build == 'linux-aarch64'
      run: sudo apt-get install binutils-aarch64-linux-gnu && aarch64-linux-gnu-strip dist/node/*.node
    - name: strip linux-armv7 builds
      if: matrix.build == 'linux-armv7'
      run: sudo apt-get install binutils-arm-linux-gnueabihf && arm-linux-gnueabihf-strip dist/node/*.node
    - name: Set artifact name
      shell: bash
      working-directory: dist/node
      run: |
        echo "ARTIFACT_NAME=$(echo highwayhasher*.node)" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v2
      with:
        path: dist/node/highwayhasher*.node
        name: ${{ env.ARTIFACT_NAME }}
        if-no-files-found: error

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@v2
      with:
        path: artifacts-temp
    - name: Flatten artifacts
      run: |
        mkdir artifacts
        find artifacts-temp -type f -exec cp '{}' artifacts/ \;
        ls -lR artifacts
    - name: Create Release
      if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
      uses: actions/github-script@v2
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log('environment', process.versions);
          const fs = require('fs').promises;
          const { repo: { owner, repo }, sha } = context;
          console.log({ owner, repo, sha });
          const tag_name = process.env.GITHUB_REF.split("/")[2];
          const release = await github.repos.createRelease({
            owner, repo,
            tag_name,
            draft: false,
            target_commitish: sha
          });

          console.log('created release', { release });

          for (let file of await fs.readdir('artifacts')) {
            console.log('uploading', file);

            await github.repos.uploadReleaseAsset({
              owner, repo,
              release_id: release.data.id,
              name: file,
              data: await fs.readFile(`artifacts/${file}`)
            });
          }
